### ISSUE TITLE
Some block rewards not showing in wallet

### ISSUE THREAD

**Issue by merkMiner** [swap-dev/micropool-gui#15]
Not sure if these are orphan blocks or what but when I prove/check the reward hash it shows as valid... But the reward doesn't show in my wallet.

Block 1161583 for example.

Last night I noticed 20 blocks in the micropool UI but only had 17 rewards in my wallet. Is there a good way to debug what is up with these specific blocks?

**Comment by skipak** [comment]
Sounds like orphans to me. It’s common to get that many with 15s block time.

**Comment by LPHuynh** [comment]
Block 1161583 was found by solopool.

To improve your odds of getting your blocks accepted by the network, make sure you're well connected to the network (sync_info), set up block notifier, and add these seed nodes as priority nodes to your daemon:
148.251.154.104:19949
144.76.190.11:19949
94.23.159.182:443
66.70.141.138:19949
195.201.186.172:19949

**Comment by merkMiner** [comment]
Can we get some kind of notifier next to the block that indicates it was an orphan block?

**Comment by sebseb7** [comment]
will do

**Comment by SPuzo** [comment]
@sebseb7 I'm solo mining micro pool found a block 1425685 but the fund's never made it to the wallet.  The wallet is sycn to the chain...

**Comment by LPHuynh** [comment]
block 1425685 was found by herominer. next version of the micropool will better indicate orphan blocks.

**Comment by SPuzo** [comment]
> block 1425685 was found by herominer. next version of the micropool will better indicate orphan blocks.

When is the new version coming out?

**Comment by pharmecis** [comment]
As soon as we can.  Please do not use Github for support requests.  This is for development work.  If you have any support questions, please direct them to our Discord.
